- name: check a number is less than 10 or not
  hosts: local
  connection: local
  vars_prompt: 
  - name: NUMBER
    prompt: please enter the number  
    private: false
  tasks: 
  - name: print this if less than 10
    ansible.builtin.debug:
      msg: "Given {{NUMBER}} is less than 10"
    when: NUMBER | int < 10  #by default its giving error if ew dont give | int

  - name: print this if given num is >= 10
    ansible.builtin.debug:
      msg: "Given {{NUMBER}} is >= 10"
    when: NUMBER | int >= 10         