- name: Install the packages
  hosts: local
  connection: local
  become: yes
  tasks: 
  - name: Install the following packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - mysql
    - postfix  