- name: command vs shell
  hosts: local
  connection: local
  tasks:
  - name: execut the command
    ansible.builtin.shell: ls -ltr > /tmp/output.txt

  - name: check the process
    ansible.builtin.shell: ps -ef
    register: output
    ansible.builtin.debug:
      msg: "{{output}}"  
